CREATE TABLE IF NOT EXISTS restaurant
(
    id                               BIGINT AUTO_INCREMENT PRIMARY KEY,
    management_number                VARCHAR(50)  NOT NULL UNIQUE,
    licensing_date                   DATE,
    close_date                       DATE,
    location_phone_number            VARCHAR(20),
    location_area                    DOUBLE,
    location_zip_code                VARCHAR(10),
    full_address                     VARCHAR(500),
    road_name_address                VARCHAR(500),
    road_name_zip_code               VARCHAR(10),
    business_name                    VARCHAR(255),
    last_modified_at                 DATETIME(6),
    data_update_type                 VARCHAR(1),
    data_updated_at                  DATETIME(6),
    industry_type                    VARCHAR(100),
    coordinate_x                     DECIMAL(19, 9),
    coordinate_y                     DECIMAL(19, 9),
    open_auth_code                   VARCHAR(50),
    male_worker_count                INT,
    female_worker_count              INT,
    surrounding_area_type            VARCHAR(100),
    grade_type                       VARCHAR(100),
    water_facility_type              VARCHAR(100),
    building_ownership_type          VARCHAR(100),
    monthly_rent                     INT,
    multi_use_business_yn            VARCHAR(10),
    total_facility_size              DOUBLE,
    traditional_business_number      VARCHAR(100),
    traditional_business_main_food   VARCHAR(255),

    created_at                       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    updated_at                       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
